# JavaScript action
name: test action kobrikx
description: kobrikx test
branding:
  icon: 'check-square'
  color: 'blue'

inputs:
  version:
    description: Version of the CLI to use
    required: false
    default: latest

runs:
  using: 'node12'
  main: './dist/index.js'
