service: krtek

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:env}
  region: ${opt:region}
  profile: ${opt:profile}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-attach-managed-policy
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${self:service}.${opt:env}.nutcorp.net
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
