service: classifier-clipper

app: ${opt:env}-${self:service}
frameworkVersion: '>=1.28.0 <2.0.0'

plugins:
  - serverless-attach-managed-policy

provider:
  name: aws
  runtime: python3.7

  stage: ${opt:env}
  region: ${opt:region}
  profile: ${opt:profile}
  memorySize: 3008
  timeout: 900

  vpc:
    securityGroupIds:
      - ${ssm:/${opt:env}/${self:service}/security_group_id}

    subnetIds:
      - ${ssm:/${opt:env}/${self:service}/private_subnet_1}
      - ${ssm:/${opt:env}/${self:service}/private_subnet_2}
      - ${ssm:/${opt:env}/${self:service}/private_subnet_3}

  # TODO: Add a sticter policy to work only with reuqired buckets
  managedPolicyArns:
    - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'

  environment:
    APP_ENV: ${opt:env}
    APP_AWS_REGION: ${opt:region}
    APP_NAME: ${self:service}
    PYTHONPATH: "/opt:/opt/python"

    STREAM_BUCKET: ${ssm:/${opt:env}/${self:service}/STREAM_BUCKET}
    CLIPPER_BUCKET: ${ssm:/${opt:env}/${self:service}/CLIPPER_BUCKET}
    REDIS_HOST: ${ssm:/${opt:env}/${self:service}/REDIS_HOST}
    REDIS_PORT: ${ssm:/${opt:env}/${self:service}/REDIS_PORT}
    API_BASIC_AUTH: ${ssm:/${opt:env}/${self:service}/API_BASIC_AUTH}
    S3_METATAGGER_BUCKET: ${ssm:/${opt:env}/${self:service}/S3_METATAGGER_BUCKET}
    RMQ_HOST: ${ssm:/${opt:env}/${self:service}/RMQ_HOST}
    RMQ_PORT: ${ssm:/${opt:env}/${self:service}/RMQ_PORT}
    RMQ_VHOST: ${ssm:/${opt:env}/${self:service}/RMQ_VHOST}
    RMQ_USERNAME: ${ssm:/${opt:env}/${self:service}/RMQ_USERNAME}
    RMQ_PASSWORD: ${ssm:/${opt:env}/${self:service}/RMQ_PASSWORD}
    METATAGGER_ROUTING_KEY: ${ssm:/${opt:env}/${self:service}/METATAGGER_ROUTING_KEY}
    ML_THUMBNAILER_BUCKET: ${ssm:/${opt:env}/${self:service}/ML_THUMBNAILER_BUCKET}

functions:
  lambda_handler:
    handler: handler.lambda_handler
    events:
      - s3:
          bucket: ${ssm:/${opt:env}/${self:service}/CLIPPER_BUCKET}
          existing: true
          event: s3:ObjectCreated:*
          MaximumRetryAttempts: 0

    # TODO: This needs to be updated for other (dev) account
    layers:
      - arn:aws:lambda:${opt:region}:160492786134:layer:Python-Elasticache:2
      - arn:aws:lambda:${opt:region}:160492786134:layer:Python-FFMPEG:6
