name: "Build IZE on push"
#env:
#  GOPATH: ./go
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Build on Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build -o ./ize ./cmd
    - name: Upload bin to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ize-ubuntu
        path: ize

  Build on MacOS:
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build -o ./ize ./cmd
    - name: Upload bin to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ize-mac
        path: ize

  Build on windows:
    runs-on: windows-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build -o ./ize ./cmd
    - name: Upload bin to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ize-win
        path: ize