name: "Build"

on:
  push:
    branches:
      - master

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
          - name: Check Out Repo
            uses: actions/checkout@v2

- name: Delete release
  uses: dev-drprasad/delete-tag-and-release@v0.2.0
  with:
    delete_release: true # default: false
    tag_name: nightly # tag name to delete
    repo: kobrikx/test # target repo (optional). defaults to repo running this action
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

- name: Create a GitHub release
  needs: build
  uses: ncipollo/release-action@v1
  with:
    tag: "nightly"
    name: Nightly release
    body: |
      Nightly release
