name: "[filtered][testnut] Infra & Apps Deploy"
defaults:
  run:
    shell: bash
env:
  AWS_REGION: us-east-1
  ENV: testnut
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  #This job compares folders and create condition to run job:
  changes:  
    runs-on: ubuntu-latest
    #Set job outputs to values from filter step. If you have more than one project, you should add more outputs.
    outputs:
      squibby: ${{ steps.filter.outputs.squibby }}
    steps:
      - uses: actions/checkout@v2
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          # Filters stored in own yaml file. We need to use path to filter file.
          filters: '.github/filters.yml'
          
  #Create infrastructure for deploying projects   
  infra:
    name: infra
    runs-on: ubuntu-latest
    env:
      SSH_PUBLIC_KEY: "<Your AWS SSH key>"
      TAG: "${GITHUB_SHA::10}"

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create AWS Profile
        run: make aws.profile

      - name: Deploy Infra
        run: make infra
        shell: bash

      - name: Save TF Output
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: .infra/env/${{ env.ENV }}/output.json
          
#Create Squibby service deploy job
 squibby:
    name: squibby
    runs-on: ubuntu-latest
    needs:
      - infra
      - changes
    # Set condition for Squibby job to run.
    if: ${{ needs.changes.outputs.squibby == 'true' }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create AWS Profile
        run: make aws.profile

      - name: Load TF Output
        uses: actions/download-artifact@v1
        with:
          name: output

      - name: Extract TF Output
        run: mv output/output.json .infra/env/${{ env.ENV }}/output.json

      - name: Login to ECR
        run: make ecr.login

      - name: Build Container
        run: make ${{ github.job }}.image

      - name: Push Image
        run: make ${{ github.job }}.push

      - name: Deploy Container
        run: make ${{ github.job }}.deploy

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
        
