name: "Build IZE on release"

on:
  workflow_dispatch:

jobs:
  Build:
    if: startsWith(github.ref, 'refs/tags/0.0.0-dev') != true
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
       go-version: 1.17.x

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set env
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: create docs
      run: |
        mkdir -p commands
        go run ./cmd gendoc
    - name: get theme in css
      run: |
       curl -o themes  https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css
    - name: convert MD to HTML
      uses: baileyjm02/markdown-to-pdf@v1
      with:
        input_dir: commands
        output_dir: docs
#        theme: themes
        # Default is true, can set to false to only get PDF files
        build_html: true
        
    - name: remove pdfs #This needs because action creates PDF by default
      run: |
        cd docs
        sudo rm *.pdf
        mv ize.html index.html

    - name: Pushes ize commands to ize.sh
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
      with:
        source_file: 'docs'
        destination_repo: 'kobrikx/homebrew-testize'
#        destination_folder: 'content'
        user_email: 'ize@hazelops.com'
        user_name: 'ize'
        commit_message: 'Add commands from Ize'
