name: "Build"
on:
  push:
    branches:
      - feature/fix01
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout in remote repo
        uses: actions/checkout@v2
        with:
          repository: 'hazelops/hzl-nutcorp-backend'
          path: 'remote'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: 'feature/fix01'

      - name: checkout in local repo
        uses: actions/checkout@v2
        with:
          path: 'local'
          ref: 'feature/fix01'

#      - name: update files in remote folder
#        run: rsync -a --delete local/ remote/

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: unnecessary

      - name: run git
        run: |
          cd remote
          git branch
          git remote -v
          git add .
          git config --global user.email "kobrikx@gmail.com"
          git config --global user.name "kobrikx"
          git commit -m "Commmit some data"
          git push


#          git branch
#          ls -a local
#          ls -a remote
#          cd remote
#          git init
#          git remote add github git@github.com:hazelops/hzl-nutcorp-backend.git
#          git clone git@github.com:hazelops/hzl-nutcorp-backend.git remote --branch feature/fix01 --single-branch
#          ls -a remote
#      - name: ddsd
#        run: |
#          rsync -a --delete local/ remote/
#          ls -a remote
#          cd remote
#          git config --global user.email "kobrikx@gmail.com"
#          git config --global user.name "kobrikx"
#          git add --all
#          git commit -m "Commit to @rjr"
#          git push -u github feature/fix01
#
#
#          git clone git@github.com:hazelops/hzl-nutcorp-backend.git
#          git checkout feature/fix01
#          rsync -a --delete local/ remote/
#          git add .
#          git commit -am "Commit to @rjr"
#          git push origin master

#          git remote add github git@github.com:hazelops/hzl-nutcorp-backend.git
#          git config --global user.email "kobrikx@gmail.com"
#          git config --global user.name "kobrikx"
#          cd remote
#          git checkout feature/fix01
#          git add --all
#          git commit -am "Commit to @rjr"
#          git push -u github feature/fix01
#7
#      - run: |
#
#          git clone git@github.com:hazelops/hzl-nutcorp-backend.git remote --branch feature/fix01 --single-branch
#          rsync -a --delete local/ remote/
#          cd remote
#          git remote add github git@github.com:hazelops/hzl-nutcorp-backend.git
#          git checkout feature/fix01
#          git add --all
#          git commit -am "Commit to @rjr"
#          git push -u github feature/fix01
#
#
#
#
#          git remote add github git@github.com:hazelops/hzl-nutcorp-backend.git
#          git config --global user.email "kobrikx@gmail.com"
#          git config --global user.name "kobrikx"
#          git checkout feature/fix01
#          git push -u github feature/fix01
#
#         --branch feature/fix01 --single-branch
# git push --set-upstream origin feature/check-dev-to-prerelease