name: "Build"

env:
  CLIENT_REPO_GIT_USER_EMAIL: "kobrikx@gmail.com"
  CLIENT_REPO_GIT_USER_NAME: "kobrikx"
  CLIENT_REPO_NAME: 'hazelops/hzl-nutcorp-backend'
on:
  push:
    branches:
      - `hzl-**`
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Compute name of remote branch
        run: |
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          REMOTE_REF=$(echo "$GIT_BRANCH" | sed 's/\hzl-//g')
          echo "REMOTE_REF=$REMOTE_REF" >> $GITHUB_ENV
          echo "$REMOTE_REF"
          echo "$GITHUB_REF"

      - name: Checkout in remote repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.CLIENT_REPO_NAME }}
          path: 'remote'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: ${{ env.REMOTE_REF }}

      - name: Checkout in local repo
        uses: actions/checkout@v2
        with:
          path: 'local'
          ref: ${{ env.GITHUB_REF }}

      - name: Update files in remote folder
        run: rsync -a --exclude=".git" --delete local/ remote/

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: unnecessary

      - name: Push changes to remote repo
        run: |
          cd remote
          git branch
          git remote -v
          git add .
          git config --global user.email ${{ env.CLIENT_REPO_GIT_USER_EMAIL }}
          git config --global user.name ${{ env.CLIENT_REPO_GIT_USER_NAME }}
          git commit -m "Commmit some data"
          git push
          