name: "Build"
on:
  push:
    branches:
      - feature/fix01
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: 'feature/fix01'
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: unnecessary
      - run: |
          git config --global user.email "kobrikx@gmail.com"
          git config --global user.name "kobrikx"
          git clone git@github.com:hazelops/hzl-nutcorp-backend.git remote --branch feature/fix01 --single-branch
#          git checkout feature/fix-01
          git clone git@github.com:kobrikx/test.git local --branch feature/fix01 --single-branch
#          git checkout
          rsync -a --delete local/ remote/
          git add remote
          git commit -am "Commit to @rjr"
          git push



#          git remote add github git@github.com:hazelops/hzl-nutcorp-backend.git
#          git config --global user.email "kobrikx@gmail.com"
#          git config --global user.name "kobrikx"
#          git checkout feature/fix01
#          git push -u github feature/fix01
#         --branch feature/fix01 --single-branch