name: "Tests: brew install"
defaults:
  run:
    shell: bash

env:
  AWS_PROFILE: default
  AWS_REGION: us-east-1

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * */2'

jobs:
  build:
    name: Install On MacOS Latest
    runs-on: macos-latest
    steps:

      - name: get ize version
        uses: rez0n/actions-github-release@main
        id: ize_release
        env:
          token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          repository: "hazelops/ize"
          type: "latest"

      - name: Install Ize
        run: |
          brew tap hazelops/ize
          brew install ize

      - name: Run Ize and compare version
        run: ize -version |grep ${{ steps.ize_release.outputs.release }}
